// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhH4Krx-utTkhpFUB8hyVYdzO0a0xV7E',
    appId: '1:630190439113:web:071530e368c1112ff4eb18',
    messagingSenderId: '630190439113',
    projectId: 'roomy-27216',
    authDomain: 'roomy-27216.firebaseapp.com',
    storageBucket: 'roomy-27216.firebasestorage.app',
    measurementId: 'G-X07JDMYMPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEIci7eTfw4CTSGX7EtS1BId4s8cbRE0',
    appId: '1:630190439113:android:cfc38202c531ab78f4eb18',
    messagingSenderId: '630190439113',
    projectId: 'roomy-27216',
    storageBucket: 'roomy-27216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLnoGcyT9tnEif5Yw4zCG_Zkl6LwVDXPE',
    appId: '1:630190439113:ios:6aa6b23a97132e86f4eb18',
    messagingSenderId: '630190439113',
    projectId: 'roomy-27216',
    storageBucket: 'roomy-27216.firebasestorage.app',
    iosBundleId: 'com.example.roomyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLnoGcyT9tnEif5Yw4zCG_Zkl6LwVDXPE',
    appId: '1:630190439113:ios:6aa6b23a97132e86f4eb18',
    messagingSenderId: '630190439113',
    projectId: 'roomy-27216',
    storageBucket: 'roomy-27216.firebasestorage.app',
    iosBundleId: 'com.example.roomyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhH4Krx-utTkhpFUB8hyVYdzO0a0xV7E',
    appId: '1:630190439113:web:93c0ae851b6eed3cf4eb18',
    messagingSenderId: '630190439113',
    projectId: 'roomy-27216',
    authDomain: 'roomy-27216.firebaseapp.com',
    storageBucket: 'roomy-27216.firebasestorage.app',
    measurementId: 'G-VY76CBL0YC',
  );

}